export const routes = {
    home: '/',
    login: '/login',
    register: '/register',
    changePassword: '/change-password',
    about: '/about',
    profile: '/profile',
    teacher: '/teachers',
    detailTeacher: '/teachers/:id',
    courses: '/courses',
    detailCourse: '/courses/:id',
    myCourse: '/my-courses',
    detailMyCourse: '/my-courses/:id',
    lectureCourse: '/courses/:courseId/lecture/:lectureId',
    quizCourse: '/courses/:courseId/quiz/:quizId',
    codeCourse: '/courses/:courseId/code/:codeId',
    schedule: '/schedule',
    message: '/message',
    payment: '/payment/:id',
    paymentrResult: '/payment-result',
    courseCompleted: '/courses/:id/completed',
    certificate: '/cretificate/:courseId/student/:studentId'
};